<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Post>
 */
class PostFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        return [
            //This line allows the faker library creates a definition for a post content of a 20-word sentence
            'body' => $this->faker->sentence(20),
        ];
        // Run the command below to create 200 records of posts generated by the Fake library assigning a user id of 3 to each post. To run the command, first run 'php artisan tinker':
        // App\Models\Post::factory()->times(200)->create(['user_id' => 3]);
    }
}
